[package]
name = "botcore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
tokio-stream = "0.1"
tokio = { version = "1.32", features = ["full"] }
tracing = "0.1"
thiserror = "2.0.11"
