name: PR Validation

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Run integration tests
        run: cargo test --test integration_test --verbose

  version-check:
    name: Version Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if version was bumped
        run: |
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:Cargo.toml | grep -m 1 'version = ' | cut -d '"' -f 2)
          PR_VERSION=$(grep -m 1 'version = ' Cargo.toml | cut -d '"' -f 2)
          if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
            echo "Error: Version in Cargo.toml has not been incremented"
            exit 1
          fi
          echo "Version was bumped from $MAIN_VERSION to $PR_VERSION"
